%% Supplementary Material – Model Generation and Sampling Workflow
% This Live Script documents the generation of disease-constrained RBC-GEM models 
% and the subsequent flux balance and flux sampling analyses. It is intended as 
% supplementary material to ensure reproducibility of the computational experiments.
%% Initialization of the COBRA Toolbox and Solver
% We begin by initializing the COBRA Toolbox and selecting the Gurobi solver, 
% which is used for both flux balance analysis (FBA) and flux sampling procedures.

initCobraToolbox(false)
changeCobraSolver('gurobi', 'all')
%% Loading the RBC-GEM Model
% The reference red blood cell genome-scale model (RBC-GEM) is loaded. A conditional 
% check is included to adapt the working directory depending on the computer hostname, 
% allowing collaborators to specify their own paths.

[~, name] = system('hostname');
name = strtrim(name);
if strcmp(name, 'Germans-MacBook-Pro.local')
    workDir = '/Users/gpreciat/work/Drive/GIMI/proyectos/MCBCI_terapiasPersonalizadas/';
else
    % TODO: @RS Pon tu directorio
    ...
end
load([workDir filesep 'datos' filesep 'model' filesep 'RBC-GEM.mat'])
%% Reference Model and Baseline FBA Solution
% The healthy model (|ModelOr|) corresponds to the unmodified RBC-GEM. An FBA 
% is performed with the default objective to obtain the baseline flux distribution, 
% which will serve as the healthy reference for subsequent comparisons. Only the 
% flux vector is stored here, though saving the full solution (including objective 
% value and duals) is recommended.

modelOr = RBC_GEM;
modelOrSol = optimizeCbModel(modelOr, 'max');
v_or = modelOrSol.v;
save('v_or', 'v_or')
%% Identification of Key Reactions
% The reactions that define the disease phenotype are identified:
%% 
% * |G6PDH2| represents glucose-6-phosphate dehydrogenase activity, the primary 
% deficient enzyme.
% * |EX_h2o2_e| represents hydrogen peroxide exchange with the extracellular 
% space.

G6PDH2_id = findRxnIDs(RBC_GEM, 'G6PDH2');
Exh2o2_id = findRxnIDs(RBC_GEM, 'EX_h2o2_e');
%% Defining Constraint Levels
% We define fractional constraints for both reactions to simulate different 
% levels of enzyme deficiency and oxidative stress.
%% 
% * *G6PDH2 constraints*: 0.1, 0.28, and 0.5 fractions of the original upper 
% bound, representing severe, moderate, and mild deficiency.
% * *EX_h2o2_e constraints*: 1, 0.75, and 0.5 fractions of the original upper 
% bound, representing full, moderate, and low clearance capacity for hydrogen 
% peroxide.

G6PDH2_constraints = [.1, .28, .5];   % fractions of original UB
Exh2o2_constraints = [1, .75, .5];    % fractions of original UB
%% Generation of Disease-Constrained Models
% For each combination of G6PDH2 and H₂O₂ constraints, a new disease model is 
% generated by modifying the reaction bounds of the healthy model.
% 
% Flux sampling is performed using the *Randomized Hit-and-Run Monte Carlo (RHMC)* 
% method, with three independent chains of 2000 samples each. This allows assessment 
% of reproducibility and variability across sampling runs.
% 
% Additionally, FBA is solved for each constrained model to obtain the corresponding 
% optimal flux distribution. All models, FBA solutions, and sampling results are 
% stored in the output directory.

for i = 1:length(G6PDH2_constraints)
    for j = 1:length(Exh2o2_constraints)
        
        % Apply constraints
        model = changeRxnBounds(modelOr, 'G6PDH2', RBC_GEM.ub(G6PDH2_id) * G6PDH2_constraints(i), 'u');
        model = changeRxnBounds(model, 'EX_h2o2_e', RBC_GEM.ub(Exh2o2_id) * Exh2o2_constraints(j), 'u');
        
        % Perform sampling (3 independent chains)
        samples1 = sampleCbModel(model, [], 'RHMC', 2000);
        samples2 = sampleCbModel(model, [], 'RHMC', 2000);
        samples3 = sampleCbModel(model, [], 'RHMC', 2000);
        
        % Solve FBA for the constrained model
        fbaSol = optimizeCbModel(model, 'max');
        
        % Format descriptive names
        g6 = strrep(num2str(G6PDH2_constraints(i)),'.','_');
        h2 = strrep(num2str(Exh2o2_constraints(j)),'.','_');
        
        % Store model under descriptive variable name
        eval(['G6PD_' g6 '_h2o2_' h2 ' = model;']);
        
        % Save outputs
        save([workDir 'resultados' filesep 'G6PD_' g6 '_h2o2_' h2], ['G6PD_' g6 '_h2o2_' h2])
        save([workDir 'resultados' filesep 'G6PD_' g6 '_h2o2_' h2 '_sol'], 'fbaSol')
        save([workDir 'resultados' filesep 'G6PD_' g6 '_h2o2_' h2 '_samples1'], 'samples1')
        save([workDir 'resultados' filesep 'G6PD_' g6 '_h2o2_' h2 '_samples2'], 'samples2')
        save([workDir 'resultados' filesep 'G6PD_' g6 '_h2o2_' h2 '_samples3'], 'samples3')
    end
end
%% Summary
% This pipeline produced nine disease-constrained RBC-GEM variants (3 × G6PDH2 
% levels × 3 × H₂O₂ levels). For each variant we stored:
%% 
% # The modified model.
% # The FBA optimal flux distribution.
% # Three independent flux sampling matrices.
%% 
% These data constitute the foundation for downstream analyses, including the 
% calculation of biological and mathematical metrics, cross-model comparisons, 
% and machine learning classification to identify therapeutic candidates.